# Video settings
video:
  path: "./videos/test.mp4"
  save_result: false
  fps: 30

# Separator line settings
line:
  x1: 0  # normalized x-coordinate of line start point (0-1)
  y1: 0  # normalized y-coordinate of line start point (0-1)
  x2: 0.5    # normalized x-coordinate of line end point (0-1)
  y2: 1    # normalized y-coordinate of line end point (0-1)
  in_side: "left"  # which side is considered "in": "left" or "right" (for horizontal lines, left means bottom)

detector:
  detector_type: "yolo"  # Options: "yolo"
  model_path: "./models/yolov8s.pt"
  class_id: 0
  input_width: 640
  input_height: 640
  conf_threshold: 0.25

# Tracking settings
tracking:
  tracker_type: "bytetrack"
  track_thresh: 0.25    # tracking confidence threshold
  track_buffer: 30     # frames to keep lost tracks
  match_thresh: 0.8    # matching threshold for tracking

# Display settings
display:
  max_width: 1280
  max_height: 720

line_crossing:
  crossing_criteria: "bottom"  # Options: "center", "top", "bottom", "left", "right", "whole_bbox"
